-- STIKDEAD :: 011 — Coleções Safira (azul, slots restantes) e Esmeralda (verde, completa)
INSERT INTO items (id, name, slot, rarity, price, currency, template, params) VALUES
('saf_face_bandana', 'Bandana do Cristal', 'face', 'diamante', 90, 'diamonds', 'bandana', '{"color":"#8fe3ff","glow":"#7fd9ff"}'),
('saf_face_mask_oni', 'Máscara Oni do Oceano', 'face', 'diamante', 115, 'diamonds', 'mask_oni', '{"color":"#4d7dff","glow":"#5d8dff"}'),
('saf_face_mask_skull', 'Caveira Celeste', 'face', 'diamante', 140, 'diamonds', 'mask_skull', '{"color":"#bfeaff","glow":"#9fe0ff"}'),
('saf_face_eyes_red', 'Olhos do Glaciar', 'face', 'diamante', 165, 'diamonds', 'eyes_red', '{"color":"#6db8ff","glow":"#7fd9ff"}'),
('saf_arms_gauntlets', 'Manoplas do Cristal', 'arms', 'diamante', 80, 'diamonds', 'gauntlets', '{"color":"#8fe3ff","glow":"#7fd9ff"}'),
('saf_arms_gloves', 'Luvas do Oceano', 'arms', 'diamante', 105, 'diamonds', 'gloves', '{"color":"#4d7dff","glow":"#5d8dff"}'),
('saf_arms_bands', 'Faixas Celeste', 'arms', 'diamante', 130, 'diamonds', 'bands', '{"color":"#bfeaff","glow":"#9fe0ff"}'),
('saf_legs_pants', 'Calças do Cristal', 'legs', 'diamante', 85, 'diamonds', 'pants', '{"color":"#8fe3ff","glow":"#7fd9ff"}'),
('saf_legs_shorts', 'Bermudas do Oceano', 'legs', 'diamante', 110, 'diamonds', 'shorts', '{"color":"#4d7dff","glow":"#5d8dff"}'),
('saf_legs_kneepads', 'Joelheiras Celeste', 'legs', 'diamante', 135, 'diamonds', 'kneepads', '{"color":"#bfeaff","glow":"#9fe0ff"}'),
('saf_feet_boots', 'Botas do Cristal', 'feet', 'diamante', 75, 'diamonds', 'boots', '{"color":"#8fe3ff","glow":"#7fd9ff"}'),
('saf_feet_shoes', 'Sapatilhas do Oceano', 'feet', 'diamante', 100, 'diamonds', 'shoes', '{"color":"#4d7dff","glow":"#5d8dff"}'),
('esm_face_bandana', 'Bandana de Esmeralda', 'face', 'diamante', 90, 'diamonds', 'bandana', '{"color":"#5dffa8","glow":"#4dee98"}'),
('esm_face_mask_oni', 'Máscara Oni da Floresta Viva', 'face', 'diamante', 115, 'diamonds', 'mask_oni', '{"color":"#2edc7a","glow":"#3ddc84"}'),
('esm_face_mask_skull', 'Caveira de Jade', 'face', 'diamante', 140, 'diamonds', 'mask_skull', '{"color":"#a8ffd4","glow":"#7dffb8"}'),
('esm_face_eyes_red', 'Olhos Venenosa', 'face', 'diamante', 165, 'diamonds', 'eyes_red', '{"color":"#0faf62","glow":"#2edc7a"}'),
('esm_arms_gauntlets', 'Manoplas de Esmeralda', 'arms', 'diamante', 80, 'diamonds', 'gauntlets', '{"color":"#5dffa8","glow":"#4dee98"}'),
('esm_arms_gloves', 'Luvas da Floresta Viva', 'arms', 'diamante', 105, 'diamonds', 'gloves', '{"color":"#2edc7a","glow":"#3ddc84"}'),
('esm_arms_bands', 'Faixas de Jade', 'arms', 'diamante', 130, 'diamonds', 'bands', '{"color":"#a8ffd4","glow":"#7dffb8"}'),
('esm_legs_pants', 'Calças de Esmeralda', 'legs', 'diamante', 85, 'diamonds', 'pants', '{"color":"#5dffa8","glow":"#4dee98"}'),
('esm_legs_shorts', 'Bermudas da Floresta Viva', 'legs', 'diamante', 110, 'diamonds', 'shorts', '{"color":"#2edc7a","glow":"#3ddc84"}'),
('esm_legs_kneepads', 'Joelheiras de Jade', 'legs', 'diamante', 135, 'diamonds', 'kneepads', '{"color":"#a8ffd4","glow":"#7dffb8"}'),
('esm_feet_boots', 'Botas de Esmeralda', 'feet', 'diamante', 75, 'diamonds', 'boots', '{"color":"#5dffa8","glow":"#4dee98"}'),
('esm_feet_shoes', 'Sapatilhas da Floresta Viva', 'feet', 'diamante', 100, 'diamonds', 'shoes', '{"color":"#2edc7a","glow":"#3ddc84"}'),
('esm_head_crown', 'Coroa de Esmeralda', 'head', 'diamante', 110, 'diamonds', 'crown', '{"color":"#5dffa8","glow":"#4dee98"}'),
('esm_head_hood', 'Capuz da Floresta Viva', 'head', 'diamante', 135, 'diamonds', 'hood', '{"color":"#2edc7a","glow":"#3ddc84"}'),
('esm_head_band', 'Banda de Jade', 'head', 'diamante', 160, 'diamonds', 'band', '{"color":"#a8ffd4","glow":"#7dffb8"}'),
('esm_body_vest', 'Veste de Esmeralda', 'body', 'diamante', 120, 'diamonds', 'vest', '{"color":"#5dffa8","glow":"#4dee98"}'),
('esm_body_scarf', 'Cachecol da Floresta Viva', 'body', 'diamante', 145, 'diamonds', 'scarf', '{"color":"#2edc7a","glow":"#3ddc84"}'),
('esm_weapon_katana', 'Katana de Esmeralda', 'weapon', 'diamante', 160, 'diamonds', 'katana', '{"color":"#5dffa8","glow":"#4dee98"}'),
('esm_weapon_spear', 'Lança da Floresta Viva', 'weapon', 'diamante', 185, 'diamonds', 'spear', '{"color":"#2edc7a","glow":"#3ddc84"}'),
('esm_weapon_axe', 'Machado de Jade', 'weapon', 'diamante', 210, 'diamonds', 'axe', '{"color":"#a8ffd4","glow":"#7dffb8"}'),
('esm_weapon_scythe', 'Foice Venenosa', 'weapon', 'diamante', 235, 'diamonds', 'scythe', '{"color":"#0faf62","glow":"#2edc7a"}'),
('esm_weapon_bow', 'Arco de Esmeralda', 'weapon', 'diamante', 260, 'diamonds', 'bow', '{"color":"#5dffa8","glow":"#4dee98"}'),
('esm_back_cape', 'Capa de Esmeralda', 'back', 'diamante', 180, 'diamonds', 'cape', '{"color":"#5dffa8","glow":"#4dee98"}'),
('esm_back_aura', 'Asas da Floresta Viva', 'back', 'diamante', 205, 'diamonds', 'aura', '{"color":"#2edc7a","glow":"#3ddc84"}'),
('esm_back_sheath', 'Bainha de Jade', 'back', 'diamante', 230, 'diamonds', 'sheath', '{"color":"#a8ffd4","glow":"#7dffb8"}'),
('esm_effect_aura', 'Aura de Esmeralda', 'effect', 'diamante', 210, 'diamonds', 'aura', '{"color":"#5dffa8","glow":"#4dee98"}'),
('esm_effect_dust', 'Cristais da Floresta Viva', 'effect', 'diamante', 235, 'diamonds', 'dust', '{"color":"#2edc7a","glow":"#3ddc84"}')
ON CONFLICT (id) DO NOTHING;
