-- STIKDEAD :: 017 — melhorias amarelas (1-2) nos itens de moedas
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'bracadeiras' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'bracadeiras_neve' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'bracadeiras_rubras' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'luvas_negras' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'luvas_void' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'manoplas' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'manoplas_carrasco' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'manoplas_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'manoplas_void' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "⭐ Item +2 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'bracadeiras_ki' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'luvas_combate' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'luvas_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'luvas_ouro' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'luvas_vermelhas' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'bainha' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'bainha_ouro' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "⭐ Item +2 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'capa_dourada' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'capa_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'capa_guerreiro' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'aura_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "⭐ Item +2 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'aura_ouro' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'aura_void' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'capa_void' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'bainha_dupla' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'capa_curta' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'capa_negra' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'capa_rubra_2' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'cachecol_cinza' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'cachecol_negro' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'colete_couro' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'armadura_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'armadura_ronin' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'cachecol_ki' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'armadura_infernal' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'armadura_ouro' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'armadura_vazio' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'cachecol_dourado' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'cachecol_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'cachecol_vermelho' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +2 — concede +3% de defesa ao lutador", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'colete' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'colete_ronin_2' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'colete_tatico' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "⭐ Item +1 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'poeira_cinzas' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'aura_vermelha' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'poeira_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'poeira_ouro' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'poeira_veneno' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'aura_caos' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'poeira_abissal' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'poeira_solar' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "⭐ Item +1 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'poeira_void' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'poeira_neve' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'poeira_pes' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'poeira_rosa' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'poeira_sangue' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'bandana_azul' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'bandana_preta' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'bandana_vermelha' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'mascara_gas' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'mascara_kitsune' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'mascara_oni' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'olhos_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'olhos_ouro' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'mascara_vazio' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "⭐ Item +2 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'olhos_void' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'bandana_caveira' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "⭐ Item +1 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'bandana_dourada' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'mascara_caveira' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'mascara_hockey' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'mascara_teatro' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'olhos_vermelhos' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'tenis_classico' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'tenis_negro' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'botas_carrasco' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'botas_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'botas_sombrias' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'tenis_void' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'botas_ouro' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'botas_void' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'botas' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +2 — concede +3% de defesa ao lutador", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'botas_neve' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'tenis_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'tenis_ouro' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'tenis_sangue' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'faixa_branca' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'faixa_branca_2' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'faixa_negra' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'faixa_vermelha' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'capuz_sangue' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'capuz_sombrio' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'coroa_espinhos' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'elmo_ronin' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'faixa_ki' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'coroa' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'coroa_sombria' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'capuz_cinzas' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'chapeu_kasa_negro' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'chapeu_palha' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'faixa_dourada' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +2 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'calca_ninja' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'joelheiras_aco' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'shorts_negro' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +2 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'shorts_treino' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'calca_gelo' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'calca_sangue' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'joelheiras_void' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'shorts_ki' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'calca_void' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'calca_ronin' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'joelheiras' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'joelheiras_ouro' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'shorts_ouro' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'estilo_berserker' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'estilo_espectro' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'estilo_monge' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'estilo_shinobi' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'bastao_bo' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'katana' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'nunchaku' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'nunchaku_aco' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +3 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'arco' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'dual_blades' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais"]'::jsonb WHERE id = 'dual_gemeas' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +2 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'foice' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +2 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'katana_dourada' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'lanca_relampago' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'machado_carrasco' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'arco_fantasma' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "⭐ Item +1 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'foice_sangrenta' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'katana_infernal' AND excellents IS NULL;
UPDATE items SET excellents = '["🗡️ Diminui 10% do Dano de Ataque recebido", "⭐ Item +2 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'katana_void' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'bo_dragao' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +1 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'foice_gelida' AND excellents IS NULL;
UPDATE items SET excellents = '["⭐ Item +2 — concede +3% de defesa ao lutador"]'::jsonb WHERE id = 'katana_jade' AND excellents IS NULL;
UPDATE items SET excellents = '["💥 Dano +2% — causa 2% a mais de dano no oponente", "🗡️ Diminui 10% do Dano de Ataque recebido"]'::jsonb WHERE id = 'lanca' AND excellents IS NULL;
UPDATE items SET excellents = '["🎯 Chance de Defesa +10% — o bloqueio absorve 10% a mais", "💥 Dano +2% — causa 2% a mais de dano no oponente"]'::jsonb WHERE id = 'machado' AND excellents IS NULL;
