-- STIKDEAD :: 028 — segunda leva diamante: 20 armas + 20 rostos (arte IA)
INSERT INTO items (id, name, slot, rarity, price, currency, template, params) VALUES
-- ===== ARMAS =====
('w2_martelo_tempestade', 'Martelo da Tempestade',   'weapon', 'diamante', 320, 'diamonds', 'crystal_axe',    '{"blade":"#cfe6ff","core":"#4da6ff","glow":"#4da6ff"}'),
('w2_kanabo_rubi',        'Kanabō de Rubi',          'weapon', 'diamante', 300, 'diamonds', 'crystal_axe',    '{"blade":"#ffd6d6","core":"#ff3b3b","glow":"#ff5a5a"}'),
('w2_naginata_aurora',    'Naginata da Aurora',      'weapon', 'diamante', 340, 'diamonds', 'crystal_spear',  '{"blade":"#ffe0f4","core":"#ff7ad9","glow":"#8fe3ff"}'),
('w2_tridente_maremoto',  'Tridente do Maremoto',    'weapon', 'diamante', 330, 'diamonds', 'crystal_spear',  '{"blade":"#d6f2ff","core":"#1f8fff","glow":"#39c1ff"}'),
('w2_cimitarra_sol',      'Cimitarra do Sol',        'weapon', 'diamante', 310, 'diamonds', 'crystal_katana', '{"blade":"#fff3cf","core":"#ffb300","glow":"#ffd76a"}'),
('w2_adaga_eclipse',      'Adaga do Eclipse',        'weapon', 'diamante', 280, 'diamonds', 'crystal_katana', '{"blade":"#e4d6ff","core":"#7a3bff","glow":"#9a5bff"}'),
('w2_garra_dragao',       'Garra do Dragão',         'weapon', 'diamante', 350, 'diamonds', 'crystal_katana', '{"blade":"#ffdccf","core":"#ff4d1f","glow":"#ff7a3b"}'),
('w2_kama_lua',           'Kama da Lua',             'weapon', 'diamante', 290, 'diamonds', 'crystal_scythe', '{"blade":"#f0f4ff","core":"#bcd0ff","glow":"#dfe8ff"}'),
('w2_tessen_vendaval',    'Tessen do Vendaval',      'weapon', 'diamante', 270, 'diamonds', 'crystal_katana', '{"blade":"#f2ffff","core":"#9adfe8","glow":"#c8f4f8"}'),
('w2_chakram_estrela',    'Chakram Estelar',         'weapon', 'diamante', 300, 'diamonds', 'crystal_katana', '{"blade":"#fff6d6","core":"#ffcf3b","glow":"#ffe27a"}'),
('w2_machadao_vulcao',    'Machadão do Vulcão',      'weapon', 'diamante', 360, 'diamonds', 'crystal_axe',    '{"blade":"#ffd9c4","core":"#ff5417","glow":"#ff8046"}'),
('w2_katana_trovao',      'Katana do Trovão',        'weapon', 'diamante', 340, 'diamonds', 'crystal_katana', '{"blade":"#fdffd6","core":"#f2e21f","glow":"#fff23b"}'),
('w2_lanca_serpente',     'Lança da Serpente',       'weapon', 'diamante', 320, 'diamonds', 'crystal_spear',  '{"blade":"#e2ffd9","core":"#48c93c","glow":"#8f5bff"}'),
('w2_foice_alma',         'Foice das Almas',         'weapon', 'diamante', 380, 'diamonds', 'crystal_scythe', '{"blade":"#eadcff","core":"#8f3bff","glow":"#b57aff"}'),
('w2_bastao_dragao',      'Bastão do Dragão',        'weapon', 'diamante', 300, 'diamonds', 'crystal_spear',  '{"blade":"#ffe4c4","core":"#ff8c1f","glow":"#ffc46a"}'),
('w2_espada_fenix',       'Espada da Fênix',         'weapon', 'diamante', 350, 'diamonds', 'crystal_katana', '{"blade":"#ffe8cf","core":"#ff6a17","glow":"#ffa53b"}'),
('w2_maca_meteoro',       'Maça do Meteoro',         'weapon', 'diamante', 310, 'diamonds', 'crystal_axe',    '{"blade":"#e8d9cf","core":"#ff7a3b","glow":"#ffb37a"}'),
('w2_kunai_sombra',       'Kunai da Sombra',         'weapon', 'diamante', 260, 'diamonds', 'crystal_katana', '{"blade":"#d9d6e8","core":"#5b4dff","glow":"#7a6aff"}'),
('w2_sabre_nebulosa',     'Sabre da Nebulosa',       'weapon', 'diamante', 370, 'diamonds', 'crystal_katana', '{"blade":"#e8dcff","core":"#c43bff","glow":"#7a9aff"}'),
('w2_alabarda_tita',      'Alabarda do Titã',        'weapon', 'diamante', 390, 'diamonds', 'crystal_spear',  '{"blade":"#ffeec4","core":"#e8a51f","glow":"#8fe3ff"}'),
-- ===== ROSTOS =====
('f2_hannya_carmesim',   'Máscara Hannya Carmesim',  'face', 'diamante', 340, 'diamonds', 'mask_oni',   '{"color":"#c41f2e","glow":"#ff5a5a"}'),
('f2_kitsune_branca',    'Máscara Kitsune Branca',   'face', 'diamante', 330, 'diamonds', 'mask_oni',   '{"color":"#f4f0e8","glow":"#ff9a3b"}'),
('f2_mempo_dourado',     'Mempō Dourado',            'face', 'diamante', 320, 'diamonds', 'mask_oni',   '{"color":"#d8a51f","glow":"#ffd76a"}'),
('f2_elmo_dragao',       'Elmo do Dragão',           'face', 'diamante', 400, 'diamonds', 'mask_oni',   '{"color":"#b3341f","glow":"#ff7a3b"}'),
('f2_cranio_demonio',    'Crânio de Demônio',        'face', 'diamante', 380, 'diamonds', 'mask_skull', '{"color":"#d8ccc4","glow":"#ff3b3b"}'),
('f2_visor_neon',        'Visor Neon',               'face', 'diamante', 290, 'diamonds', 'mask_oni',   '{"color":"#17e8f4","glow":"#3bffea"}'),
('f2_mascara_corvo',     'Máscara de Corvo',         'face', 'diamante', 310, 'diamonds', 'mask_oni',   '{"color":"#2b2b33","glow":"#8f9aff"}'),
('f2_tengu_rubro',       'Máscara Tengu Rubra',      'face', 'diamante', 330, 'diamonds', 'mask_oni',   '{"color":"#d8341f","glow":"#ff8046"}'),
('f2_capacete_gladiador','Capacete do Gladiador',    'face', 'diamante', 350, 'diamonds', 'mask_oni',   '{"color":"#c4a53b","glow":"#ffe27a"}'),
('f2_mascara_teatro',    'Máscara do Teatro Sombrio','face', 'diamante', 300, 'diamonds', 'mask_oni',   '{"color":"#e8e4dc","glow":"#b57aff"}'),
('f2_cabeca_lobo',       'Cabeça de Lobo',           'face', 'diamante', 390, 'diamonds', 'mask_oni',   '{"color":"#8a8a94","glow":"#c8d4e8"}'),
('f2_mascara_gato',      'Máscara do Gato da Sorte', 'face', 'diamante', 280, 'diamonds', 'mask_oni',   '{"color":"#f4f0e8","glow":"#ff5a5a"}'),
('f2_elmo_ciclope',      'Elmo do Ciclope',          'face', 'diamante', 360, 'diamonds', 'mask_oni',   '{"color":"#6a7a8a","glow":"#3bffea"}'),
('f2_mascara_fantasma',  'Máscara do Fantasma',      'face', 'diamante', 290, 'diamonds', 'mask_skull', '{"color":"#f4f4f4","glow":"#c8d4e8"}'),
('f2_respirador_toxico', 'Respirador Tóxico',        'face', 'diamante', 310, 'diamonds', 'mask_oni',   '{"color":"#4a5a3b","glow":"#7dff3b"}'),
('f2_mascara_borboleta', 'Máscara Borboleta',        'face', 'diamante', 300, 'diamonds', 'mask_oni',   '{"color":"#9a5bff","glow":"#ff7ad9"}'),
('f2_elmo_tubarao',      'Elmo Tubarão',             'face', 'diamante', 350, 'diamonds', 'mask_oni',   '{"color":"#6a8a9a","glow":"#8fe3ff"}'),
('f2_mascara_palhaco',   'Máscara do Palhaço Macabro','face','diamante', 320, 'diamonds', 'mask_oni',   '{"color":"#e8e4dc","glow":"#ff3b3b"}'),
('f2_mascara_medusa',    'Máscara da Medusa',        'face', 'diamante', 370, 'diamonds', 'mask_oni',   '{"color":"#48a93c","glow":"#7dff9a"}'),
('f2_mascara_kabuki',    'Máscara Kabuki',           'face', 'diamante', 300, 'diamonds', 'mask_oni',   '{"color":"#f4f0e8","glow":"#d8341f"}')
ON CONFLICT (id) DO NOTHING;
