-- STIKDEAD :: 035 — poda de costas + a revoada das 10 asas (com balões)
DELETE FROM gifts WHERE item_id IN ('dia_bainha_gelo','dia_capa_cometa','esm_back_cape','esm_back_sheath');
DELETE FROM loadouts WHERE item_id IN ('dia_bainha_gelo','dia_capa_cometa','esm_back_cape','esm_back_sheath');
DELETE FROM user_items WHERE item_id IN ('dia_bainha_gelo','dia_capa_cometa','esm_back_cape','esm_back_sheath');
DELETE FROM items WHERE id IN ('dia_bainha_gelo','dia_capa_cometa','esm_back_cape','esm_back_sheath');
INSERT INTO items (id, name, slot, rarity, price, currency, template, params, excellents) VALUES ('bk_asa_fenix', 'Asas da Fênix', 'back', 'diamante', 420, 'diamonds', 'aura', '{"color":"#8fe3ff","glow":"#bfefff"}', '["🔥 Voo da Fênix — renasce mais forte a cada round", "❤️ Aumenta HP Máximo +4%", "🧿 Energia Máxima +4%", "🪞 Reflete Dano +5% — devolve parte do dano recebido"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO items (id, name, slot, rarity, price, currency, template, params, excellents) VALUES ('bk_asa_dragao', 'Asas de Dragão', 'back', 'diamante', 430, 'diamonds', 'aura', '{"color":"#8fe3ff","glow":"#bfefff"}', '["🐉 Envergadura do Dragão — presença que domina a arena", "🛡️ Aumenta a Defesa +Nível/20 — defesa cresce com o nível", "❤️ Aumenta HP Máximo +4%", "❄️ Redução de Dano +4% — dano recebido reduzido"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO items (id, name, slot, rarity, price, currency, template, params, excellents) VALUES ('bk_asa_serafim', 'Asas de Serafim', 'back', 'diamante', 450, 'diamonds', 'aura', '{"color":"#8fe3ff","glow":"#bfefff"}', '["😇 Luz Divina — proteção celestial", "❄️ Redução de Dano +4% — dano recebido reduzido", "❤️ Aumenta HP Máximo +4%", "🧿 Energia Máxima +4%", "🎯 Chance de Bloqueio +10% — maior chance de defender ataques"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO items (id, name, slot, rarity, price, currency, template, params, excellents) VALUES ('bk_asa_demonio', 'Asas do Demônio', 'back', 'diamante', 430, 'diamonds', 'aura', '{"color":"#8fe3ff","glow":"#bfefff"}', '["😈 Voo Sombrio — o medo chega antes de você", "🪞 Reflete Dano +5% — devolve parte do dano recebido", "❄️ Redução de Dano +4% — dano recebido reduzido", "🧿 Energia Máxima +4%"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO items (id, name, slot, rarity, price, currency, template, params, excellents) VALUES ('bk_asa_borboleta', 'Asas de Borboleta', 'back', 'diamante', 380, 'diamonds', 'aura', '{"color":"#8fe3ff","glow":"#bfefff"}', '["🦋 Dança Etérea — flutue entre os golpes", "❄️ Redução de Dano +4% — dano recebido reduzido", "🧿 Energia Máxima +4%", "🎯 Chance de Bloqueio +10% — maior chance de defender ataques"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO items (id, name, slot, rarity, price, currency, template, params, excellents) VALUES ('bk_asa_tempestade', 'Asas da Tempestade', 'back', 'diamante', 410, 'diamonds', 'aura', '{"color":"#8fe3ff","glow":"#bfefff"}', '["⚡ Vento Elétrico — dash recarrega 10% mais rápido", "🧿 Energia Máxima +4%", "❄️ Redução de Dano +4% — dano recebido reduzido", "🎯 Chance de Bloqueio +10% — maior chance de defender ataques"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO items (id, name, slot, rarity, price, currency, template, params, excellents) VALUES ('bk_asa_sombra', 'Asas das Sombras', 'back', 'diamante', 400, 'diamonds', 'aura', '{"color":"#8fe3ff","glow":"#bfefff"}', '["🌑 Manto Noturno — invisível aos olhos comuns", "❄️ Redução de Dano +4% — dano recebido reduzido", "🪞 Reflete Dano +5% — devolve parte do dano recebido", "🧿 Energia Máxima +4%"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO items (id, name, slot, rarity, price, currency, template, params, excellents) VALUES ('bk_asa_morcego', 'Asas de Morcego Rubi', 'back', 'diamante', 390, 'diamonds', 'aura', '{"color":"#8fe3ff","glow":"#bfefff"}', '["🦇 Eco Vampírico — golpes drenam vigor do rival", "❤️ Aumenta HP Máximo +4%", "🪞 Reflete Dano +5% — devolve parte do dano recebido", "❄️ Redução de Dano +4% — dano recebido reduzido"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO items (id, name, slot, rarity, price, currency, template, params, excellents) VALUES ('bk_asa_mecanica', 'Asas Mecânicas', 'back', 'diamante', 410, 'diamonds', 'aura', '{"color":"#8fe3ff","glow":"#bfefff"}', '["⚙️ Propulsão a Cristal — engenharia de outro mundo", "🛡️ Aumenta a Defesa +Nível/20 — defesa cresce com o nível", "🧿 Energia Máxima +4%", "🎯 Chance de Bloqueio +10% — maior chance de defender ataques"]'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO items (id, name, slot, rarity, price, currency, template, params, excellents) VALUES ('bk_asa_arcoiris', 'Asas do Arco-Íris', 'back', 'diamante', 440, 'diamonds', 'aura', '{"color":"#8fe3ff","glow":"#bfefff"}', '["🌈 Espectro Vivo — todas as cores lutam com você", "❤️ Aumenta HP Máximo +4%", "🧿 Energia Máxima +4%", "❄️ Redução de Dano +4% — dano recebido reduzido", "🎯 Chance de Bloqueio +10% — maior chance de defender ataques"]'::jsonb) ON CONFLICT (id) DO NOTHING;
